export const API_ENDPOINTS = {
    SEARCH_USERS: "/api/search/users",
    LOGIN: "/api/auth/login",
    REGISTER: "/api/auth/register",
    FETCH_MESSAGES: "/api/messages/fetch",
    GENERATE_TOKEN: "/api/token/generate",
    ADMIN_MESSAGES_STORE: "/api/admin/messages/store",
    TEMPLATE_SELECT: "/api/template/select",
    UPDATE_BACKGROUND_COLOLR: "/api/update/bgColor",
    GET_USER_CHATS : "/api/get/messages",
    ADMIN_MESSAGE_READ : "/api/admin/messages/read",
    ADMIN_MESSAGE_READ : "/api/admin/messages/read",
    USER_MESSAGE_READ : "/api/user/messages/read",
    FETCH_LATEST_MESSAGE : "/api/user/latest/messages",
};